"""Evidence base: 155 source-derived references, the capability baseline,
and the incident register.

``SOURCES`` carries exactly the 155 source-derived bibliography keys —
the 65-key v0.1.0 backbone, the 85-key v0.2.0 extension, and the 5-key
v0.3.0 author-work extension (research verified 2026-09-11) — with their
pinned URLs, the same key/URL pairs the BibTeX contract enforces in
``manuscript/references.bib`` and that manuscript prose may cite. Tiers
classify how a claim is attributed:

- ``official`` — vendor or project documentation and release policy.
- ``advisory`` — coordinated security advisories and trackers.
- ``incident_report`` — the reporting party's own incident or
  campaign account (vendor findings, not independent measurements).
- ``research`` — research programs and assessment bodies.
- ``community`` — community wikis and developer discussions used for
  specific integration caveats.

``CAPABILITY_BASELINE`` pins the offensive/defensive AI numbers the
source assessment reports (NCSC forecast, Anthropic campaign, AISI
testing incident, DARPA AIxCC, QSB-118 fix, NixOS 26.05 support end).
Every number is the reporting party's own figure with the attribution
caveats recorded in the matching ``Source.claims``.

``INCIDENTS`` registers the documented platform and agent incidents the
review's boundary lessons are drawn from; each entry pairs one
reporting-party account with the citation key it is attributed to.

No I/O at import time; the module is a pure constant surface.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = [
    "Source",
    "TIER_VOCAB",
    "SOURCES",
    "Incident",
    "INCIDENTS",
    "CAPABILITY_BASELINE",
    "sources_by_tier",
]


@dataclass(frozen=True)
class Source:
    """One source-derived reference: key, attribution metadata, tier, claims."""

    key: str
    title: str
    publisher: str
    year: int
    url: str
    tier: str
    claims: tuple[str, ...]


#: Attribution-tier vocabulary for :data:`SOURCES`.
TIER_VOCAB: tuple[str, ...] = ("official", "advisory", "incident_report", "research", "community")

#: The 65-key v0.1.0 backbone — keys and URLs exactly as pinned by the
#: shared brief's BibTeX contract (key/URL parity with ``references.bib``).
_SOURCE_BACKBONE: tuple[Source, ...] = (
    Source(
        "redhat_errata_policy",
        "Support policy for updates and errata",
        "Red Hat",
        2026,
        "https://access.redhat.com/support/policy/updates/errata",
        "official",
        ("Formal security-errata classification and maintenance phases underpin RHEL's supported-operation planning.",),
    ),
    Source(
        "alpine_design",
        "About Alpine Linux",
        "Alpine Linux",
        2026,
        "https://alpinelinux.org/about/",
        "official",
        ("Small musl/BusyBox-based system documenting PIE and stack-smashing protection for userland binaries.",),
    ),
    Source(
        "alpine_support_scope",
        "Alpine Linux releases",
        "Alpine Linux",
        2026,
        "https://alpinelinux.org/releases/",
        "official",
        ("Roughly two-year main-repository support versus community-repository support only until the next stable release.",),
    ),
    Source(
        "nixos_hardened_profile_deprecation",
        "Proposal to deprecate the hardened profile",
        "NixOS Discourse",
        2026,
        "https://discourse.nixos.org/t/proposal-to-deprecate-the-hardened-profile/63081",
        "community",
        ("Maintainer discussion argues the profile lacks a coherent baseline and particular restrictions can undermine browser sandboxing without compensating setup.",),
    ),
    Source(
        "nixos_rollback_data_discussion",
        "Rolling back data as well, not only Nix config",
        "NixOS Discourse",
        2026,
        "https://discourse.nixos.org/t/rolling-back-data-as-well-not-only-nix-config/63169",
        "community",
        ("Community discussion of the mismatch when a service's database has migrated but its software is rolled back.",),
    ),
    Source(
        "nix_cache_signatures",
        "What guarantees do signatures by binary caches give?",
        "NixOS Discourse",
        2026,
        "https://discourse.nixos.org/t/what-guarantees-do-signatures-by-binary-caches-give/34802",
        "community",
        ("Trusting a cache signer is distinct from proving an output was produced by the expected derivation.",),
    ),
    Source(
        "qubes_43_release_notes",
        "Qubes OS 4.3 release notes",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/developer/releases/4_3/release-notes.html",
        "official",
        ("GUI/admin-domain splitting, new device-assignment mechanisms, and initial Wayland-related work.",),
    ),
    Source(
        "qubes_qrexec",
        "Qrexec: policy-controlled inter-domain services",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/developer/services/qrexec.html",
        "official",
        ("Qrexec mediates every cross-domain communication through explicit policy rather than free connectivity.",),
    ),
    Source(
        "qubes_architecture",
        "Qubes OS architecture",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/developer/system/architecture.html",
        "official",
        ("Application domains under the bare-metal Xen hypervisor with networking kept out of the privileged administrative domain.",),
    ),
    Source(
        "qubes_gui_protocol",
        "GUI protocol",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/developer/system/gui.html",
        "official",
        ("Keyboard and mouse events are directed to the focused domain; inter-domain clipboard transfer requires explicit user action.",),
    ),
    Source(
        "qubes_security_design_goals",
        "Security design goals",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/developer/system/security-design-goals.html",
        "official",
        ("Isolation between applications within the same qube is explicitly not promised.",),
    ),
    Source(
        "qubes_faq",
        "Qubes OS FAQ",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/introduction/faq.html",
        "official",
        ("Dom0 compromise is described as fatal to the security model; a successful hypervisor escape could compromise the whole system.",),
    ),
    Source(
        "qubes_gui_domain",
        "GUI domain",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/user/advanced-topics/gui-domain.html",
        "official",
        ("Advanced GUI-domain deployment modes are distinguished; some are suitable only for testing.",),
    ),
    Source(
        "qubes_disposables",
        "How to use disposable qubes",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/user/how-to-guides/how-to-use-disposables.html",
        "official",
        ("Disposable qubes discard their changes when their lifecycle ends, supporting disposable hostile intake.",),
    ),
    Source(
        "qubes_anti_evil_maid",
        "Anti Evil Maid",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/user/security-in-qubes/anti-evil-maid.html",
        "official",
        ("The documented AEM path has specific TPM/Intel TXT requirements and operational hazards.",),
    ),
    Source(
        "qubes_templates",
        "Templates",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/user/templates/templates.html",
        "official",
        ("Template-backed qubes see a read-only root; community templates receive no Qubes-project updates.",),
    ),
    Source(
        "fedora_coreos_updates",
        "Fedora CoreOS auto-updates",
        "Fedora Project",
        2026,
        "https://docs.fedoraproject.org/en-US/fedora-coreos/auto-updates/",
        "official",
        ("Atomic deployments with Zincati-coordinated updates and retained previous deployments for rollback.",),
    ),
    Source(
        "fedora_silverblue_technical",
        "Fedora Silverblue technical information",
        "Fedora Project",
        2026,
        "https://docs.fedoraproject.org/en-US/fedora-silverblue/technical-information/",
        "official",
        ("Read-only system paths with writable /etc and /var on the atomic desktop.",),
    ),
    Source(
        "fedora_selinux_getting_started",
        "SELinux getting started",
        "Fedora Project",
        2026,
        "https://docs.fedoraproject.org/en-US/quick-docs/selinux-getting-started/",
        "official",
        ("The existence of SELinux does not by itself establish a tight sandbox for each application as deployed.",),
    ),
    Source(
        "fedora_release_lifecycle",
        "Fedora release lifecycle",
        "Fedora Project",
        2026,
        "https://docs.fedoraproject.org/en-US/releases/lifecycle/",
        "official",
        ("Approximately 13-month release support window requires regular upgrades.",),
    ),
    Source(
        "flatpak_permissions",
        "Flatpak sandbox permissions",
        "Flatpak",
        2026,
        "https://docs.flatpak.org/en/latest/sandbox-permissions.html",
        "official",
        ("A restrictive basic sandbox coexists with permission grants that expand access, including a warning about unrestricted bus access.",),
    ),
    Source(
        "ubuntu_core_confinement",
        "Ubuntu Core security and sandboxing",
        "Canonical",
        2026,
        "https://documentation.ubuntu.com/core/explanation/security-and-sandboxing/",
        "official",
        ("AppArmor, seccomp, device controls, and mount namespaces documented for snaps on the all-snap appliance edition.",),
    ),
    Source(
        "snap_confinement",
        "Snap confinement",
        "Canonical",
        2026,
        "https://documentation.ubuntu.com/security/security-features/privilege-restriction/snap-confinement/",
        "official",
        ("Strict, classic, and development snap modes are distinguished; classic snaps have no confinement.",),
    ),
    Source(
        "opensuse_aeon",
        "Portal:Aeon",
        "openSUSE",
        2026,
        "https://en.opensuse.org/Portal:Aeon",
        "official",
        ("Immutable Tumbleweed-based desktop.",),
    ),
    Source(
        "opensuse_transactional_update",
        "Transactional update",
        "openSUSE",
        2026,
        "https://en.opensuse.org/Transactional-update",
        "official",
        ("Changes are prepared in a new snapshot without modifying the running system.",),
    ),
    Source(
        "fedora_selinux_config",
        "SELinux/Config",
        "Fedora Project",
        2026,
        "https://fedoraproject.org/wiki/SELinux/Config",
        "official",
        ("SELinux enforcing documented as the Fedora default baseline.",),
    ),
    Source(
        "genode_sculpt",
        "Genode / Sculpt",
        "Genode Labs",
        2026,
        "https://genode.org/download/sculpt",
        "official",
        ("General-purpose OS from a microkernel architecture with capability-based security, sandboxed drivers, and VMs; 26.04 release in day-to-day use by its developers.",),
    ),
    Source(
        "nix_ghsa_g3g9",
        "GHSA-g3g9-5vj6-r3gj: symlink-following flaw during fixed-output derivation registration",
        "NixOS",
        2026,
        "https://github.com/NixOS/nix/security/advisories/GHSA-g3g9-5vj6-r3gj",
        "advisory",
        ("Users permitted to submit builds could gain root in multi-user installations including with sandboxed Linux builds; fixes listed for 2.34.5 and 2.33.4.",),
    ),
    Source(
        "qubes_issue_4371",
        "Secure Boot engineering discussion (qubes-issues 4371)",
        "Qubes OS Project",
        2026,
        "https://github.com/QubesOS/qubes-issues/issues/4371",
        "community",
        ("Merely signing the bootloader or Xen is insufficient for boot integrity.",),
    ),
    Source(
        "qubes_issue_7992",
        "Qubes NixOS-template integration (qubes-issues 7992)",
        "Qubes OS Project",
        2026,
        "https://github.com/QubesOS/qubes-issues/issues/7992",
        "community",
        ("Community NixOS-template work in progress; integration and maintenance risk remains.",),
    ),
    Source(
        "bottlerocket_security_features",
        "Bottlerocket security features",
        "Bottlerocket OS",
        2026,
        "https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_FEATURES.md",
        "official",
        ("Read-only dm-verity root, enforcing SELinux, stateless /etc, kernel lockdown, no host shell; goals distinguish host persistence resistance, vulnerability mitigation, and protection between containers.",),
    ),
    Source(
        "lanzaboote_repo",
        "Lanzaboote",
        "nix-community",
        2026,
        "https://github.com/nix-community/lanzaboote",
        "official",
        ("Work remains before upstream integration; key management is explicitly outside the project's full scope.",),
    ),
    Source(
        "talos_repo",
        "Talos Linux",
        "Sidero Labs",
        2026,
        "https://github.com/siderolabs/talos",
        "official",
        ("Kubernetes-specific OS with no shell or interactive console, API-only mutual-TLS management, and atomic updates.",),
    ),
    Source(
        "grapheneos_features",
        "GrapheneOS features",
        "GrapheneOS Foundation",
        2026,
        "https://grapheneos.org/features",
        "official",
        ("Hardening atop Android's security model keeps even Google Play inside the standard app sandbox.",),
    ),
    Source(
        "nix_store_secrets",
        "Nix store secrets",
        "NixOS",
        2026,
        "https://nix.dev/manual/nix/2.33/store/secrets.html",
        "official",
        ("The store is readable by all users and secrets can reach external caches; read secrets at runtime with suitable access controls.",),
    ),
    Source(
        "nix_sandbox_config",
        "Nix sandbox configuration",
        "NixOS",
        2026,
        "https://nix.dev/manual/nix/2.35/command-ref/conf-file.html",
        "official",
        ("The documented sandbox concerns builds, with specified exceptions such as network access for fixed-output derivations.",),
    ),
    Source(
        "nixos_2605_announcement",
        "NixOS 26.05 release announcement",
        "NixOS",
        2026,
        "https://nixos.org/blog/announcements/2026/nixos-2605/",
        "official",
        ("Seven months of bug fixes and security updates ending 2026-12-31.",),
    ),
    Source(
        "parrot_intended_use",
        "What is Parrot?",
        "Parrot Security",
        2026,
        "https://parrotsec.org/docs/introduction/what-is-parrot/",
        "official",
        ("Documents hardening measures while the core remains tuned for security and forensics.",),
    ),
    Source(
        "nixos_reproducibility",
        "NixOS reproducibility project",
        "NixOS",
        2026,
        "https://reproducible.nixos.org/",
        "official",
        ("Dependency specification and sandboxing alone do not guarantee reproducible outputs; remaining sources of nondeterminism are documented.",),
    ),
    Source(
        "secureblue_features",
        "secureblue features",
        "secureblue",
        2026,
        "https://secureblue.dev/features",
        "official",
        ("Fedora Atomic base, broad hardened_malloc, confined Trivalent browser, SUID-root removal, Xwayland disabled, user-namespace restrictions with documented exceptions, signed-container policy.",),
    ),
    Source(
        "sel4_verification_assumptions",
        "seL4 verification assumptions",
        "seL4 Foundation",
        2026,
        "https://sel4.systems/Verification/assumptions.html",
        "official",
        ("Proofs are scoped by explicit assumptions including boot, hardware, and DMA-related qualifications.",),
    ),
    Source(
        "tails_overview",
        "About Tails",
        "Tor Project",
        2026,
        "https://tails.net/about/index.en.html",
        "official",
        ("Amnesic live environment with Tor networking.",),
    ),
    Source(
        "tails_persistent_storage",
        "Tails Persistent Storage",
        "Tor Project",
        2026,
        "https://tails.net/doc/persistent_storage/",
        "official",
        ("Optional encrypted Persistent Storage; information exposed during the active session is not recoverable afterward.",),
    ),
    Source(
        "nixos_security_tracker",
        "Nixpkgs security tracker",
        "NixOS",
        2026,
        "https://tracker.security.nixos.org/",
        "advisory",
        ("Coordinates matching and mitigation of vulnerabilities in Nixpkgs.",),
    ),
    Source(
        "ubuntu_release_cycle",
        "Ubuntu release cycle",
        "Canonical",
        2026,
        "https://ubuntu.com/about/release-cycle",
        "official",
        ("Five years of standard security maintenance for LTS releases; Core is not Ubuntu Desktop LTS with an immutability switch.",),
    ),
    Source(
        "nixos_lanzaboote_wiki",
        "Lanzaboote",
        "NixOS Wiki",
        2026,
        "https://wiki.nixos.org/wiki/Lanzaboote",
        "community",
        ("Lanzaboote characterized as in development.",),
    ),
    Source(
        "nixos_wiki",
        "NixOS",
        "NixOS Wiki",
        2026,
        "https://wiki.nixos.org/wiki/NixOS",
        "community",
        ("Declarative system configuration with generation-based activation and rollback.",),
    ),
    Source(
        "nixos_rebuild_wiki",
        "Nixos-rebuild",
        "NixOS Wiki",
        2026,
        "https://wiki.nixos.org/wiki/Nixos-rebuild",
        "community",
        ("Documented operation switches system generations; rollback does not restore mutable service state.",),
    ),
    Source(
        "nixos_security_wiki",
        "Security",
        "NixOS Wiki",
        2026,
        "https://wiki.nixos.org/wiki/Security",
        "community",
        ("Incomplete SELinux integration and, as of April 2026, incomplete AppArmor integration.",),
    ),
    Source(
        "anthropic_campaign_report",
        "Anthropic campaign investigation",
        "Anthropic",
        2025,
        "https://www-cdn.anthropic.com/d7dd50dd1185f59be051b307150d877f2b82bd2c.pdf",
        "incident_report",
        ("November 2025 investigation reported a campaign targeting roughly 30 entities with a handful of validated intrusions and substantial agent involvement; the model sometimes overstated findings or fabricated unusable credentials.",),
    ),
    Source(
        "aisi_incident_report",
        "Incident report: unsanctioned agent behaviour during cyber testing",
        "UK AI Security Institute",
        2026,
        "https://www.aisi.gov.uk/blog/incident-report-unsanctioned-agent-behaviour-during-cyber-testing",
        "incident_report",
        ("July 25-28, 2026 testing: out-of-scope internet actions in 10 of 122 runs; agents did not escape the VM sandbox; internet access was intentionally available and classifiers disabled; no real-world harm found.",),
    ),
    Source(
        "darpa_aixcc_results",
        "DARPA AI Cyber Challenge results",
        "DARPA",
        2025,
        "https://www.darpa.mil/news/2025/aixcc-results",
        "research",
        ("Competition systems discovered and patched real, non-synthetic flaws in the competition's software.",),
    ),
    Source(
        "debian_lts",
        "Debian LTS",
        "Debian",
        2026,
        "https://www.debian.org/lts/",
        "official",
        ("LTS extends stable support under a separate group from the Debian security team.",),
    ),
    Source(
        "debian_security",
        "Debian security",
        "Debian",
        2026,
        "https://www.debian.org/security/",
        "official",
        ("Coordinated security-advisory process recommending unattended security upgrades.",),
    ),
    Source(
        "kali_intended_use",
        "Should I use Kali Linux?",
        "Offensive Security",
        2026,
        "https://www.kali.org/docs/introduction/should-i-use-kali-linux/",
        "official",
        ("Penetration testing and security auditing documented as the distribution's purpose.",),
    ),
    Source(
        "kicksecure_sysmaint_split",
        "Dev/user-sysmaint split",
        "Kicksecure",
        2026,
        "https://www.kicksecure.com/wiki/Dev/user-sysmaint-split",
        "official",
        ("User/sysmaintenance boot-role split; verified boot labeled planned.",),
    ),
    Source(
        "kicksecure_hardening",
        "Operating system hardening",
        "Kicksecure",
        2026,
        "https://www.kicksecure.com/wiki/Operating_System_Hardening",
        "official",
        ("Debian-based hardening documentation explicitly contains research and non-default proposals that can cause breakage.",),
    ),
    Source(
        "ncsc_ai_cyber_threat",
        "The impact of AI on the cyber threat through 2027",
        "UK NCSC",
        2026,
        "https://www.ncsc.gov.uk/report/impact-ai-cyber-threat-now-2027",
        "research",
        ("AI is already assisting reconnaissance, vulnerability research, exploit development, and social engineering; increasingly effective exploitation of known vulnerabilities forecast through 2027; fully automated end-to-end advanced attacks unlikely within that horizon.",),
    ),
    Source(
        "openbsd_innovations",
        "OpenBSD innovations",
        "OpenBSD",
        2026,
        "https://www.openbsd.org/innovations.html",
        "official",
        ("Sustained whole-system mitigation discipline including privilege separation and W^X.",),
    ),
    Source(
        "openbsd_security",
        "OpenBSD security",
        "OpenBSD",
        2026,
        "https://www.openbsd.org/security.html",
        "official",
        ("Secure-by-default service choices and system-wide hardening.",),
    ),
    Source(
        "qsb_118",
        "QSB-118: arbitrary command injection into dom0 via qvm-copy-to-vm",
        "Qubes OS Project",
        2026,
        "https://www.qubes-os.org/news/2026/08/29/qsb-118/",
        "advisory",
        ("An already compromised qube could inject an arbitrary command into dom0 when the user initiated qvm-copy-to-vm from dom0; qubes-core-dom0-linux 4.3.22 in dom0 is the fixing package for Qubes 4.3.",),
    ),
    Source(
        "qubes_qsb_index",
        "Qubes security bulletins",
        "Qubes OS Project",
        2026,
        "https://www.qubes-os.org/security/qsb/",
        "advisory",
        ("Advisory index includes processor and Xen vulnerabilities; strong compartmentalization is not physical separation.",),
    ),
    Source(
        "talos_secureboot",
        "Talos Linux Secure Boot",
        "Sidero Labs",
        2026,
        "https://www.talos.dev/v1.11/talos-guides/install/bare-metal-platforms/secureboot/",
        "official",
        ("Signed unified kernel image containing the OS; depends on supported boot mode, enrolled keys, and actual deployment.",),
    ),
    Source(
        "whonix_technical_design",
        "Whonix technical introduction",
        "Whonix",
        2026,
        "https://www.whonix.org/wiki/Dev/Technical_Introduction",
        "official",
        ("Gateway/workstation split targets anonymity.",),
    ),
    Source(
        "whonix_workstation_security",
        "Whonix Workstation security",
        "Whonix",
        2026,
        "https://www.whonix.org/wiki/Whonix-Workstation_Security",
        "official",
        ("Compromise exposes the workstation's credentials and browser data; it does not make an authorized agent harmless.",),
    ),
)



#: The 85-key v0.2.0 extension (verified 2026-09-11) — exact key/URL parity
#: with the research dossier's new-bibliography contract plus the
#: OpenAI-Hugging Face incident technical report.
_SOURCES_V020: tuple[Source, ...] = (
    Source(
        "ncsc_ai_threat_2024",
        "The near-term impact of AI on the cyber threat",
        "UK NCSC",
        2024,
        "https://www.ncsc.gov.uk/report/impact-of-ai-on-cyber-threat",
        "research",
        ("The January 2024 NCSC assessment of AI's near-term cyber-threat impact; the earlier baseline against which the May 2025 update must be read.",),
    ),
    Source(
        "cisa_agentic_guidance",
        "Careful Adoption of Agentic AI Services",
        "CISA (Five Eyes)",
        2026,
        "https://www.cisa.gov/resources-tools/resources/careful-adoption-agentic-ai-services",
        "official",
        ("2026-04-30 Five Eyes guidance: sandboxed deployment, low-risk tasks first, threat-model-based evaluations, and red-teaming for agentic AI adoption.",),
    ),
    Source(
        "anthropic_misuse_aug_2025",
        "Detecting and countering misuse of AI: August 2025 report",
        "Anthropic",
        2025,
        "https://www.anthropic.com/news/detecting-countering-misuse-aug-2025",
        "incident_report",
        ("GTG-2002 vibe-hacking against at least 17 targets with 48-72 hour extortion deadlines; GTG-5004 sold AI-developed ransomware on underground forums.",),
    ),
    Source(
        "anthropic_ti_sept_2026",
        "Threat intelligence report: September 2026",
        "Anthropic",
        2026,
        "https://www.anthropic.com/threat-intelligence-report-september-2026",
        "incident_report",
        ("API-key theft patterns and vibe hacking persisting as the leading observed AI threat.",),
    ),
    Source(
        "mitre_c0062",
        "ATT&CK campaign C0062",
        "MITRE",
        2026,
        "https://attack.mitre.org/campaigns/C0062/",
        "advisory",
        ("ATT&CK canonization of the Anthropic-reported GTG-1002 campaign as a named campaign.",),
    ),
    Source(
        "arstechnica_gtg_skepticism",
        "Researchers question Anthropic claim that AI-assisted attack was 90% autonomous",
        "Ars Technica",
        2025,
        "https://arstechnica.com/security/2025/11/researchers-question-anthropic-claim-that-ai-assisted-attack-was-90-autonomous/",
        "research",
        ("Independent skepticism about the 80-90% autonomy framing of GTG-1002; balance citation for vendor-reported autonomy percentages.",),
    ),
    Source(
        "openai_disruption_oct_2025",
        "Disrupting malicious uses of AI: October 2025",
        "OpenAI",
        2025,
        "https://openai.com/global-affairs/disrupting-malicious-uses-of-ai-october-2025/",
        "incident_report",
        ("October 2025 counterpoint: actors repurpose existing tactics rather than develop genuinely new offensive capability.",),
    ),
    Source(
        "openai_disruption_2026",
        "Disrupting malicious uses of AI: consolidated reporting",
        "OpenAI",
        2026,
        "https://openai.com/global-affairs/disrupting-malicious-uses-of-ai/",
        "incident_report",
        ("Consolidated disruption reporting through February 2026 covering enforcement against malicious use of the models.",),
    ),
    Source(
        "gtig_prompting_autonomy",
        "From prompting to autonomy: the evolution of adversarial AI",
        "Google Threat Intelligence",
        2026,
        "https://cloud.google.com/blog/topics/threat-intelligence/from-prompting-to-autonomy-the-evolution-of-adversarial-ai",
        "incident_report",
        ("September 2026 GTIG report describing an autonomous multi-agent credential-harvesting framework and the first believed AI-assisted zero-day.",),
    ),
    Source(
        "aisi_incident_pdf",
        "Security incident INC-2026-07-28-01 (full report)",
        "UK AI Security Institute",
        2026,
        "https://cdn.prod.website-files.com/663bd486c5e4c81588db7a1d/6a724858f7db25c81487016d_Security%20Incident%20INC-2026-07-28-01.pdf",
        "incident_report",
        ("Full incident report published 2026-08-04: 19 unsanctioned live-internet actions across 10 of 122 runs on 7 models; most serious attempt used fake GitHub identities to pressure an open-source maintainer.",),
    ),
    Source(
        "darpa_aixcc_finals",
        "AIxCC finals winners announcement",
        "DARPA AI Cyber Challenge",
        2025,
        "https://aicyberchallenge.com/finals-winners-announcement/",
        "research",
        ("DEF CON finals (August 2025): Team Atlanta won; 86% of synthetic vulnerabilities identified and 68% patched, with 18 real non-synthetic vulnerabilities found by finalists.",),
    ),
    Source(
        "aixcc_atlantis_paper",
        "ATLANTIS: technical report on the AIxCC-winning pipeline",
        "arXiv",
        2025,
        "https://doi.org/10.48550/arxiv.2509.14589",
        "research",
        ("Peer-documented architecture of the AIxCC-winning automated vulnerability-discovery and patching pipeline.",),
    ),
    Source(
        "agent_cyber_benchmark",
        "Agentic cyber benchmark",
        "arXiv",
        2026,
        "https://arxiv.org/html/2603.11214v2",
        "research",
        ("Controlled benchmark measuring offensive cyber capability of autonomous agents against synthetic targets.",),
    ),
    Source(
        "openai_hf_incident",
        "OpenAI-Hugging Face incident technical report",
        "OpenAI",
        2026,
        "https://cdn.openai.com/pdf/67869394-cb91-4c12-888c-5cbd85c7814c/OpenAI-Hugging%20Face%20Incident-Technical-Report.pdf",
        "incident_report",
        ("July 2026 report: GPT-5.6 Sol long-horizon internal evaluation reaching Hugging Face infrastructure across roughly 17,600 actions; Preparedness rated the incident Critical.",),
    ),
    Source(
        "qubes_430_release",
        "Qubes OS 4.3.0 has been released",
        "Qubes OS Project",
        2025,
        "https://www.qubes-os.org/news/2025/12/21/qubes-os-4-3-0-has-been-released/",
        "official",
        ("General availability 2025-12-21 on dom0 Fedora 41 with Xen 4.19; sys-gui/sys-gui-gpu/sys-gui-vnc split and a per-target disposable management qube salt security model.",),
    ),
    Source(
        "qsb_110",
        "QSB-110 security bulletin",
        "Qubes OS Project",
        2026,
        "https://www.qubes-os.org/news/2026/03/17/qsb-110/",
        "advisory",
        ("March 2026 entry in the documented 2026 QSB cadence.",),
    ),
    Source(
        "qsb_115",
        "QSB-115 security bulletin",
        "Qubes OS Project",
        2026,
        "https://www.qubes-os.org/news/2026/06/09/qsb-115/",
        "advisory",
        ("June 2026 entry in the documented 2026 QSB cadence.",),
    ),
    Source(
        "qsb_116",
        "QSB-116 security bulletin",
        "Qubes OS Project",
        2026,
        "https://www.qubes-os.org/news/2026/07/28/qsb-116/",
        "advisory",
        ("July 2026 entry in the documented 2026 QSB cadence.",),
    ),
    Source(
        "qubes_43_requirements",
        "Qubes OS 4.3 system requirements",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/r4.3/user/hardware/system-requirements.html",
        "official",
        ("Raised hardware minimums for 4.3 with VT-d mandatory, documented on the 4.3 requirements page.",),
    ),
    Source(
        "qubes_salt_administration",
        "Salt administration in Qubes OS",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/en/latest/user/advanced-topics/salt.html",
        "official",
        ("Salt management runs from a per-target disposable management qube — the security model introduced after QSB-45.",),
    ),
    Source(
        "qubes_devices_api",
        "Qubes devices API",
        "Qubes OS Project",
        2026,
        "https://doc.qubes-os.org/projects/core-admin/en/latest/qubes-devices.html",
        "official",
        ("The 4.3 Devices API with per-qube device assignment policy including devices_denied.",),
    ),
    Source(
        "trenchboot_aem_uefi",
        "Anti Evil Maid on UEFI via TrenchBoot",
        "3mdeb",
        2025,
        "https://beta.blog.3mdeb.com/2025/2025-06-10-aem-uefi/",
        "research",
        ("Engineering analysis of porting AEM measured-boot flow to UEFI via the TrenchBoot project.",),
    ),
    Source(
        "nix_ghsa_vh5x",
        "GHSA-vh5x-56v6-4368: NAR parser unbounded recursion",
        "NixOS",
        2026,
        "https://github.com/NixOS/nix/security/advisories/GHSA-vh5x-56v6-4368",
        "advisory",
        ("High-severity NAR parser unbounded recursion with recursion bounded at depth 64 in the fix.",),
    ),
    Source(
        "nix_ghsa_gr92",
        "GHSA-gr92-w2r5-qw5p: path traversal on --unpack (CVE-2026-44029)",
        "NixOS",
        2026,
        "https://github.com/NixOS/nix/security/advisories/GHSA-gr92-w2r5-qw5p",
        "advisory",
        ("Path traversal on --unpack fixed in the current 2.35 line.",),
    ),
    Source(
        "nix_ghsa_6h4g",
        "GHSA-6h4g-g5j9-fm5f: recursive-Nix TOCTOU (CVE-2026-64846)",
        "NixOS",
        2026,
        "https://github.com/NixOS/nix/security/advisories/GHSA-6h4g-g5j9-fm5f",
        "advisory",
        ("Recursive-Nix time-of-check-to-time-of-use flaw fixed in the 2.35.0 line only.",),
    ),
    Source(
        "nix_2_35_notes",
        "Nix 2.35 release notes",
        "nix.dev",
        2026,
        "https://nix.dev/manual/nix/2.35/release-notes/rl-2.35",
        "official",
        ("Sandbox xattr blocking, build traces, and secrets guidance promoted to a first-class manual chapter.",),
    ),
    Source(
        "lanzaboote_packaging_pr",
        "nixpkgs PR 496059: Lanzaboote upstreaming",
        "NixOS",
        2026,
        "https://github.com/NixOS/nixpkgs/pull/496059",
        "community",
        ("Lanzaboote remains un-upstreamed with the packaging pull request still open; measured boot (PCR) support landed separately in April 2026.",),
    ),
    Source(
        "nixpkgs_source_provenance",
        "nixpkgs PR 425478: meta.sourceProvenance required",
        "NixOS",
        2026,
        "https://github.com/NixOS/nixpkgs/pull/425478",
        "official",
        ("Nixpkgs now requires meta.sourceProvenance, making build-input provenance a declared attribute of every package.",),
    ),
    Source(
        "trustix_rebuilt",
        "Trustix: rebuilt-binary comparison",
        "nix-community",
        2026,
        "https://github.com/nix-community/trustix",
        "research",
        ("Distributed log and comparison tooling for verifying that substitute binaries match locally rebuilt outputs.",),
    ),
    Source(
        "sbomnix",
        "sbomnix: SBOM generation for Nix",
        "TII",
        2026,
        "https://github.com/tiiuae/sbomnix",
        "research",
        ("CycloneDX/SPDX SBOM generation with SLSA provenance attestations for Nix derivations.",),
    ),
    Source(
        "nixos_reproducibility_iso",
        "nixos.iso_gnome reproducibility report",
        "reproducible.nixos.org",
        2026,
        "https://reproducible.nixos.org/nixos-iso-gnome-r13y/",
        "official",
        ("Measured full-path reproducibility of 95.18 percent for the GNOME ISO image.",),
    ),
    Source(
        "reproducible_study_2025",
        "Large-scale rebuild study of NixOS packages",
        "arXiv",
        2025,
        "https://arxiv.org/pdf/2501.15919",
        "research",
        ("Independent large-scale rebuild study measuring real-world reproducibility across the Nixpkgs package set.",),
    ),
    Source(
        "nixos_hardening_wiki",
        "NixOS Hardening wiki",
        "NixOS wiki",
        2026,
        "https://wiki.nixos.org/wiki/NixOS_Hardening",
        "community",
        ("The community hardening wiki designated as the replacement for the removed hardened distribution profile.",),
    ),
    Source(
        "nix_hardened_removed",
        "nixpkgs PR 501199: hardened distribution profile removed",
        "NixOS",
        2026,
        "https://github.com/NixOS/nixpkgs/pull/501199",
        "official",
        ("The hardened profile was fully removed, merged 2026-03-22, and is listed as a backward incompatibility in the 26.05 release notes.",),
    ),
    Source(
        "secureblue_v491",
        "secureblue v4.9.1 release notes",
        "secureblue",
        2026,
        "https://github.com/secureblue/secureblue/releases/tag/v4.9.1",
        "official",
        ("The SUID-less baseline ships in v4.9.1, completing the removal of SUID-root programs as a default.",),
    ),
    Source(
        "secureblue_v430",
        "secureblue v4.3.0 release notes",
        "secureblue",
        2026,
        "https://github.com/secureblue/secureblue/releases/tag/v4.3.0",
        "official",
        ("SELinux-restricted user namespaces as a default-deny posture; v4.4.0 renamed Chromium Hardened to Trivalent with a SELinux policy RPM subpackage.",),
    ),
    Source(
        "fedora_wayland_only",
        "Changes/WaylandOnlyGNOME",
        "Fedora Project",
        2026,
        "https://fedoraproject.org/wiki/Changes/WaylandOnlyGNOME",
        "official",
        ("Wayland-only GNOME removes X11 packages from Fedora 43/44, retiring the Xwayland-heavy fallback path.",),
    ),
    Source(
        "debian_trixie",
        "Debian 13 'Trixie' release information",
        "Debian",
        2025,
        "https://www.debian.org/releases/trixie/index.en.html",
        "official",
        ("Debian 13 released 2025-08-09 with full support to 2028-08 and LTS to 2030-06-30; Debian 14 plans a reproducible-packages mandate.",),
    ),
    Source(
        "ubuntu_2604_security",
        "Ubuntu 26.04 LTS security updates",
        "Canonical",
        2026,
        "https://ubuntu.com/blog/ubuntu-26-04-lts-security-updates",
        "official",
        ("AppArmor enforcement for OpenLDAP, experimental snap permission prompting, and SSSD running non-root.",),
    ),
    Source(
        "kicksecure_verified_boot",
        "Verified Boot",
        "Kicksecure",
        2026,
        "https://www.kicksecure.com/wiki/Verified_Boot",
        "official",
        ("Kicksecure verified boot remains documented as planned rather than deployed.",),
    ),
    Source(
        "talos_1_12_notes",
        "Talos Linux v1.12.0 release notes",
        "Sidero Labs",
        2025,
        "https://github.com/siderolabs/talos/releases/tag/v1.12.0",
        "official",
        ("Configurable TPM PCRs with default PCR 7 and PCR 11 policies and grubUseUKICmdline as the default boot configuration.",),
    ),
    Source(
        "talos_secureboot_docs",
        "Talos Secure Boot documentation",
        "Sidero Labs",
        2026,
        "https://docs.siderolabs.com/talos/v1.12/platform-specific-installations/bare-metal-platforms/secureboot",
        "official",
        ("Unified-kernel-image Secure Boot path with signed UKI and systemd-boot documentation.",),
    ),
    Source(
        "ubuntu_core_26_fde",
        "Ubuntu Core full disk encryption",
        "Canonical",
        2026,
        "https://documentation.ubuntu.com/core/explanation/full-disk-encryption/index.html",
        "official",
        ("Ubuntu Core 26 pairs TPM-sealed LUKS2 with OP-TEE-backed key protection under 15-year maintenance.",),
    ),
    Source(
        "firecracker_jailer_advisory",
        "AWS security bulletin 2026-003: Firecracker jailer (CVE-2026-1386)",
        "AWS",
        2026,
        "https://aws.amazon.com/security/security-bulletins/2026-003-AWS/",
        "advisory",
        ("Jailer symlink flaw allowing arbitrary host file overwrite; fixed in 1.13.2 and 1.14.1.",),
    ),
    Source(
        "firecracker_jailer_docs",
        "Firecracker jailer documentation",
        "Firecracker",
        2026,
        "https://github.com/firecracker-microvm/firecracker/blob/main/docs/jailer.md",
        "official",
        ("Jailer security model: explicit file-descriptor passing, cgroup and namespace isolation around the microVM manager.",),
    ),
    Source(
        "gvisor_security_policy",
        "gVisor security policy",
        "gVisor",
        2026,
        "https://gvisor.dev/security/",
        "official",
        ("Documented sandbox-wide CVE scope policy distinguishing what a gVisor vulnerability may expose.",),
    ),
    Source(
        "gvisor_seccheck",
        "gVisor SecCheck documentation",
        "gVisor",
        2026,
        "https://github.com/google/gvisor/blob/master/pkg/sentry/seccheck/README.md",
        "official",
        ("SecCheck event-sourcing observability hooks for auditing sandbox activity.",),
    ),
    Source(
        "linux_landlock_docs",
        "Landlock: unprivileged access control",
        "Linux kernel documentation",
        2026,
        "https://docs.kernel.org/userspace-api/landlock.html",
        "official",
        ("Landlock ABI 11 adds capability and namespace restriction on top of the NO_NEW_PRIVS flag.",),
    ),
    Source(
        "seccomp_pin_args",
        "seccomp user-notify PIN_ARGS",
        "LWN.net",
        2026,
        "https://lwn.net/Articles/1070987/",
        "community",
        ("Seccomp user-notify argument pinning, explicitly motivated by AI-agent sandboxing requirements.",),
    ),
    Source(
        "io_uring_hardening",
        "io_uring hardening",
        "System Hardening",
        2026,
        "https://www.systemshardening.com/articles/linux/io-uring-hardening/",
        "research",
        ("Sysctl hardening and disablement options for io_uring, the source of over a hundred kernel CVEs.",),
    ),
    Source(
        "ubuntu_restricted_userns",
        "Ubuntu 23.10 restricted unprivileged user namespaces",
        "Canonical",
        2026,
        "https://ubuntu.com/blog/ubuntu-23-10-restricted-unprivileged-user-namespaces",
        "official",
        ("Ubuntu restricts unprivileged user namespaces through AppArmor profiles from 23.10 onward.",),
    ),
    Source(
        "userns_debate_lwn",
        "User namespace attack-surface debate",
        "LWN.net",
        2026,
        "https://lwn.net/Articles/1079640/",
        "community",
        ("Developer-press coverage of the contested tradeoff between userns convenience and kernel attack surface.",),
    ),
    Source(
        "openbsd_78",
        "OpenBSD 7.8 release",
        "OpenBSD",
        2025,
        "https://www.openbsd.org/78.html",
        "official",
        ("OpenBSD 7.8 released 2025-10-22, continuing the pledge/unveil mitigation line.",),
    ),
    Source(
        "openbsd_79",
        "OpenBSD 7.9 release",
        "OpenBSD",
        2026,
        "https://www.openbsd.org/79.html",
        "official",
        ("OpenBSD 7.9 (2026-05-19) adds __pledge_open(2) and a pinsyscall PT_LOAD check.",),
    ),
    Source(
        "openbsd_errata78",
        "OpenBSD 7.8 errata",
        "OpenBSD",
        2026,
        "https://www.openbsd.org/errata78.html",
        "advisory",
        ("2026 errata remove pledge tmppath (015-018) and fix a pledge namei race (047).",),
    ),
    Source(
        "sel4_2026_news",
        "seL4 project news 2026",
        "seL4 Foundation",
        2026,
        "https://www.sel4.systems/news/2026.html",
        "official",
        ("seL4 16.0.0 (July 2026) with MCS functional verification completed on 64-bit RISC-V and the first AArch64 confidentiality proof.",),
    ),
    Source(
        "microkit_2_3",
        "Microkit 2.3.0 release",
        "seL4 Foundation",
        2026,
        "https://docs.sel4.systems/releases/microkit/2.3.0",
        "official",
        ("Microkit 2.3.0 adds x86_64 IOMMU support for static seL4 system descriptions.",),
    ),
    Source(
        "sculpt_26_04",
        "Sculpt OS release 26.04",
        "Genode Labs",
        2026,
        "https://genode.org/news/sculpt-os-release-26.04",
        "official",
        ("Sculpt 26.04 (2026-04-30): platform-driver gatekeeper, IOMMU DMA confinement, and the 'black hole' drop zone component.",),
    ),
    Source(
        "grapheneos_releases",
        "GrapheneOS releases",
        "GrapheneOS Foundation",
        2026,
        "https://grapheneos.org/releases",
        "official",
        ("2026 releases add per-app hardened_malloc opt-outs, USB-C pogo five-mode protection, and sandboxed Play hardening.",),
    ),
    Source(
        "tails_7_12",
        "Tails 7.12 release notes",
        "Tor Project",
        2026,
        "https://tails.net/news/version_7.12/",
        "official",
        ("Tails 7.12 is current in the 7.x series based on Debian 13, with a Secure Boot certificate expiry notice recorded in 7.7.",),
    ),
    Source(
        "whonix_18_support",
        "Whonix 17 end of security support and deprecation notice",
        "Whonix forums",
        2026,
        "https://forums.whonix.org/t/whonix-17-end-of-security-support-and-deprecation-notice-all-users-should-move-to-whonix-18-as-soon-as-possible/22644",
        "community",
        ("Whonix 17 reached end of security support in 2026; 18 is the only supported line.",),
    ),
    Source(
        "cloud_hypervisor_v52",
        "Cloud Hypervisor v52.0 released",
        "Cloud Hypervisor",
        2026,
        "https://www.cloudhypervisor.org/blog/cloud-hypervisor-v52.0-released/",
        "official",
        ("v52.0 fixes CVE-2026-45782 in the Rust VMM.",),
    ),
    Source(
        "owasp_agentic_tm",
        "Agentic AI Threats and Mitigations",
        "OWASP",
        2025,
        "https://genai.owasp.org/resource/agentic-ai-threats-and-mitigations/",
        "research",
        ("OWASP agentic threat taxonomy v1.0 (February 2025) including memory-poisoning and tool-misuse classes.",),
    ),
    Source(
        "owasp_agentic_top10",
        "OWASP Top 10 for Agentic Applications",
        "OWASP",
        2025,
        "https://genai.owasp.org/2025/12/09/owasp-top-10-for-agentic-applications-the-benchmark-for-agentic-security-in-the-age-of-autonomous-ai/",
        "research",
        ("December 2025 benchmark enumerating the ten dominant agentic application risk classes.",),
    ),
    Source(
        "csa_maestro",
        "MAESTRO: agentic AI threat modeling framework",
        "Cloud Security Alliance",
        2025,
        "https://cloudsecurityalliance.org/blog/2025/02/06/agentic-ai-threat-modeling-framework-maestro",
        "research",
        ("Seven-layer threat-modeling framework for agent-to-agent and agent-to-environment interactions.",),
    ),
    Source(
        "csa_securing_swarm",
        "Securing the Swarm",
        "Cloud Security Alliance",
        2026,
        "https://cloudsecurityalliance.org/blog/2026/06/24/securing-the-swarm-governance-attack-surfaces-and-zero-trust-architectures-in-multi-agent-ai-environments",
        "research",
        ("Governance, attack surfaces, and zero-trust architectures for multi-agent environments including AegisSwarm short-lived identities.",),
    ),
    Source(
        "csa_agent_insider",
        "Agents in the Wire: AI agent insider threat",
        "Cloud Security Alliance",
        2026,
        "https://labs.cloudsecurityalliance.org/wp-content/uploads/2026/03/AI-agent-insider-threat-autonomous-compromise-v1-csa-styled.pdf",
        "research",
        ("March 2026 insider-threat model treating autonomous agent compromise as an insider problem.",),
    ),
    Source(
        "mcp_spec_changelog",
        "MCP specification changelog (2025-06-18)",
        "MCP project",
        2025,
        "https://modelcontextprotocol.io/specification/2025-06-18/changelog",
        "official",
        ("MCP servers specified as OAuth Resource Servers per RFC 9728 with RFC 8707 audience-bound tokens and OAuth 2.1 plus PKCE.",),
    ),
    Source(
        "mcp_tools_annotations",
        "MCP tools: annotations",
        "MCP project",
        2025,
        "https://modelcontextprotocol.io/specification/2025-06-18/server/tools",
        "official",
        ("Tool annotations are advisory hints for UX and review, explicitly not security guarantees.",),
    ),
    Source(
        "mcp_registry_preview",
        "MCP registry preview",
        "MCP project",
        2025,
        "https://blog.modelcontextprotocol.io/posts/2025-09-08-mcp-registry-preview/",
        "official",
        ("Registry preview launched 2025-09-08 and grew to roughly 2,000 entries by November 2025.",),
    ),
    Source(
        "mcp_spec_2025_11",
        "First MCP anniversary: 2025-11-25 specification",
        "MCP project",
        2025,
        "https://blog.modelcontextprotocol.io/posts/2025-11-25-first-mcp-anniversary/",
        "official",
        ("SEP-1024 local-install security, SEP-835 default scopes, and SEP-1036 URL-mode elicitation with browser-based OAuth.",),
    ),
    Source(
        "a2a_protocol",
        "Agent2Agent (A2A) protocol",
        "Linux Foundation",
        2026,
        "https://a2a-protocol.org/latest/",
        "official",
        ("Mandatory TLS with standard HTTP authentication schemes; agents remain opaque to one another.",),
    ),
    Source(
        "anthropic_sandboxing",
        "Claude Code sandboxing",
        "Anthropic",
        2025,
        "https://www.anthropic.com/engineering/claude-code-sandboxing",
        "official",
        ("Bubblewrap/seatbelt filesystem isolation plus proxy-mediated egress with allowlists as the documented coding-agent baseline.",),
    ),
    Source(
        "anthropic_contain_claude",
        "How we contain Claude",
        "Anthropic",
        2026,
        "https://www.anthropic.com/engineering/how-we-contain-claude",
        "official",
        ("Vendor engineering account of the containment stack used for agentic deployments.",),
    ),
    Source(
        "codex_sandboxing",
        "Codex sandboxing architecture",
        "OpenAI",
        2026,
        "https://openai-codex.mintlify.app/architecture/sandboxing",
        "official",
        ("Seatbelt, Bubblewrap, Landlock, and Windows DACL enforcement derived from a single SandboxPolicy definition.",),
    ),
    Source(
        "gemini_cli_sandbox",
        "Gemini CLI sandboxing",
        "Google",
        2026,
        "https://google-gemini.github.io/gemini-cli/docs/cli/sandbox.html",
        "official",
        ("Selectable seatbelt, Docker, gVisor, and bubblewrap sandbox backends.",),
    ),
    Source(
        "nist_ai_agent_standards",
        "NIST AI Agent Standards Initiative",
        "NIST",
        2026,
        "https://www.nist.gov/artificial-intelligence/ai-agent-standards-initiative",
        "official",
        ("February 2026 initiative coordinating agent interoperability and assurance standards.",),
    ),
    Source(
        "nist_ai_600_1",
        "NIST AI 600-1: Generative AI Profile",
        "NIST",
        2024,
        "https://nvlpubs.nist.gov/nistpubs/ai/nist.ai.600-1.pdf",
        "official",
        ("Profile establishing risk-management practices for generative AI including human gates on consequential actions.",),
    ),
    Source(
        "eu_ai_act_transparency",
        "Guidelines on AI transparency obligations (Article 50)",
        "European Commission",
        2026,
        "https://digital-strategy.ec.europa.eu/en/policies/guidelines-ai-transparency-obligations",
        "official",
        ("Article 50 transparency duties applicable from 2026-08-02 with disclosure expectations for AI agents.",),
    ),
    Source(
        "ietf_agent_identity",
        "draft-klrc-aiagent-auth: agent identity and authorization",
        "IETF",
        2026,
        "https://datatracker.ietf.org/doc/draft-klrc-aiagent-auth/",
        "official",
        ("Drafts composing SPIFFE/WIMSE with OAuth 2.0 token exchange (RFC 8693) and transaction tokens; no ratified standard yet.",),
    ),
    Source(
        "aisi_inspect_framework",
        "Inspect framework",
        "UK AI Security Institute",
        2026,
        "https://inspect.aisi.org.uk/",
        "research",
        ("Inspect evaluation framework and Sandboxing Toolkit; the isolation-classification protocol adopted across AISI/CAISI/METR/Apollo.",),
    ),
    Source(
        "aisi_control_red_team",
        "How our Control Red Team is stress-testing frontier monitors",
        "UK AI Security Institute",
        2026,
        "https://www.aisi.gov.uk/blog/how-our-new-control-red-team-is-stress-testing-frontier-monitors",
        "research",
        ("AISI program red-teaming frontier-model control monitors against adaptive agents.",),
    ),
    Source(
        "apollo_automode",
        "Pilot auto-mode campaign",
        "Apollo Research",
        2026,
        "https://apolloresearch.ai/monitoring/pilot-automode-campaign",
        "research",
        ("Empirical monitoring campaign evaluating auto-mode classifiers against scheming and misuse behaviors.",),
    ),
    Source(
        "shade_arena",
        "SHADE-Arena: sabotage monitoring evaluations",
        "Anthropic",
        2025,
        "https://www.anthropic.com/research/shade-arena-sabotage-monitoring",
        "research",
        ("June 2025 evaluations of monitor ability to detect agent sabotage in realistic multi-task environments.",),
    ),
    Source(
        "claude_code_auto_mode",
        "Claude Code auto mode",
        "Anthropic",
        2026,
        "https://www.anthropic.com/engineering/claude-code-auto-mode",
        "official",
        ("Two-stage review: classifier-gated execution with escalation to explicit user approval for consequential actions.",),
    ),
)


#: The 5-key v0.3.0 author-work extension (verified 2026-09-11) — the
#: author's Zenodo-deposited cognitive-security works, cited in the
#: manuscript where their concepts do work (show-not-tell placement).
_SOURCES_V030: tuple[Source, ...] = (
    Source(
        "cogsecskills2026",
        "CogSecSkills: Multiharness Agentic Skills for Cognitive Security",
        "Zenodo",
        2026,
        "https://zenodo.org/records/21520558",
        "research",
        (
            "Software, v1.0.0, 2026-07-24: roughly 100 inspectable skills in 7 taxonomy groups "
            "(structured analytic techniques, deception detection, source verification, "
            "critical review) runnable under the same harnesses; GitHub docxology/CogSecSkills.",
        ),
    ),
    Source(
        "cif_formal_2026",
        "Cognitive Integrity Framework: Formal Foundations (Part 1 of 3)",
        "Zenodo",
        2026,
        "https://zenodo.org/records/22134544",
        "research",
        (
            "Preprint v2.0, 2026-08-26: Trust Calculus with δ-bounded delegation, Defense "
            "Composition Algebra, and info-theoretic stealth-impact bounds; verification of "
            "belief integrity, trust boundedness, and goal preservation; corresponds with "
            "the OWASP Agentic Top-10.",
        ),
    ),
    Source(
        "cif_validation_2026",
        "Cognitive Integrity Framework Part 2: Computational Validation and Implementation",
        "Zenodo",
        2026,
        "https://zenodo.org/records/18364128",
        "research",
        (
            "Part 2 of the CIF series: computational validation and implementation of the "
            "Part-1 formal model.",
        ),
    ),
    Source(
        "cif_practitioner_2026",
        "Cognitive Integrity Framework: Practical Applications and Deployment Guide (Part 3)",
        "Zenodo",
        2026,
        "https://zenodo.org/records/22134548",
        "research",
        (
            "Preprint v2.0: operator posture assessment, human-oversight checklists, agent "
            "security invariants, subagent hardening, and incident-response playbooks; "
            "CIF-AD-OODA goal-hijacking analysis across ten domains.",
        ),
    ),
    Source(
        "ageint2026",
        "AGEINT: Agentic Intelligence Curriculum",
        "Zenodo",
        2026,
        "https://zenodo.org/records/20732274",
        "research",
        (
            "Curriculum for agentic-intelligence tradecraft; the educational upstream of "
            "CogSecSkills.",
        ),
    ),
)

#: All source-derived references — 155 keys with pinned URLs (65-key v0.1.0
#: backbone plus the 85-key v0.2.0 extension plus the 5-key v0.3.0
#: author-work extension; key/URL parity with ``manuscript/references.bib``).
SOURCES: tuple[Source, ...] = _SOURCE_BACKBONE + _SOURCES_V020 + _SOURCES_V030


@dataclass(frozen=True)
class Incident:
    """One documented incident the review's boundary lessons are drawn from.

    Every field is the reporting party's own account — dates and counts
    carry the attribution caveats recorded in the matching
    :data:`SOURCES` entry for ``citation_key``.
    """

    incident_id: str
    date: str
    actor_class: str
    vector: str
    boundary_lesson: str
    citation_key: str


#: The incident register — 14 documented incidents spanning agent-driven
#: intrusions, authorized-agent misbehavior, and platform boundary
#: failures. Citation keys must exist in ``manuscript/references.bib``.
INCIDENTS: tuple[Incident, ...] = (
    Incident(
        "gtg-1002",
        "2025-11",
        "external_threat_agent",
        "AI-agent-assisted intrusion campaign targeting roughly 30 entities with a handful of validated intrusions.",
        "Vendor-reported autonomy percentages are attribution-caveated, not independent measurements; human decision points remained in the loop.",
        "anthropic_campaign_report",
    ),
    Incident(
        "gtg-2002",
        "2025-08",
        "human_operator",
        "Vibe hacking: human operators conducting intrusions with AI assistance against at least 17 targets with 48-72 hour extortion deadlines.",
        "Extortion speed compresses recovery time; rehearsed recovery and credential revocation are the compensating controls.",
        "anthropic_misuse_aug_2025",
    ),
    Incident(
        "anthropic_apikey_theft",
        "2026-09",
        "external_threat_actor",
        "API-key theft patterns persisting as a leading observed AI threat in the September 2026 threat-intelligence report.",
        "Long-lived cloud credentials are the agent operator's crown jewels; scope credentials to a task and revoke at boundary crossings.",
        "anthropic_ti_sept_2026",
    ),
    Incident(
        "aisi_inc_2026_07_28_01",
        "2026-07-25..28",
        "authorized_agent",
        "Unsanctioned live-internet actions across 10 of 122 runs on 7 models during authorized cyber testing, including fake GitHub identities pressuring a maintainer.",
        "Authorized agents misbehave within authorization, not through sandbox escape; classifier coverage and mediation points bound the authorized-misuse surface.",
        "aisi_incident_pdf",
    ),
    Incident(
        "openai_hf_2026",
        "2026-07",
        "authorized_agent",
        "Long-horizon internal evaluation agent reaching Hugging Face infrastructure across roughly 17,600 actions; Preparedness rated the incident Critical.",
        "Egress boundaries must separate evaluation scopes from production infrastructure, not merely internal from external networks.",
        "openai_hf_incident",
    ),
    Incident(
        "qsb-110",
        "2026-03-17",
        "local_attacker",
        "Qubes security bulletin fixing dom0-relevant vulnerabilities in the March 2026 cadence.",
        "A documented bulletin cadence keeps the dom0 attack surface visible between releases; update operations are part of the boundary.",
        "qsb_110",
    ),
    Incident(
        "qsb-115",
        "2026-06-09",
        "local_attacker",
        "Qubes security bulletin fixing dom0-relevant vulnerabilities in the June 2026 cadence.",
        "Scheduled bulletins without a named campaign still move the dom0 attack surface; track the cadence as a standing control.",
        "qsb_115",
    ),
    Incident(
        "qsb-116",
        "2026-07-28",
        "local_attacker",
        "Qubes security bulletin fixing dom0-relevant vulnerabilities in the July 2026 cadence.",
        "Update operations for the isolation layer are part of the boundary, not an afterthought to it.",
        "qsb_116",
    ),
    Incident(
        "qsb-118",
        "2026-08-28",
        "local_attacker",
        "Arbitrary command injection into dom0 via qvm-copy-to-vm (CVE-2026-82636, CVSS 7.9) from an already compromised qube; fixed by qubes-core-dom0-linux 4.3.22.",
        "A user-initiated copy is a trust-boundary crossing into the TCB; mediate operations, not vague intentions.",
        "qsb_118",
    ),
    Incident(
        "nix_ghsa_g3g9",
        "2026",
        "local_attacker",
        "Symlink-following flaw during fixed-output derivation registration let build-submission users gain root in multi-user installations.",
        "Build submission is a privileged operation; sandboxed Linux builds did not remove the underlying privilege boundary.",
        "nix_ghsa_g3g9",
    ),
    Incident(
        "nix_ghsa_vh5x",
        "2026",
        "local_attacker",
        "NAR parser unbounded recursion converting artifact ingestion into denial of service; recursion bounded at depth 64 in the fix.",
        "Parser robustness is a supply-chain trust boundary; unbounded input handling in a trusted path is itself a vulnerability.",
        "nix_ghsa_vh5x",
    ),
    Incident(
        "cve_2026_44029",
        "2026",
        "local_attacker",
        "Path traversal on nix --unpack (GHSA-gr92-w2r5-qw5p) escaping the intended extraction directory.",
        "Extraction is a filesystem-boundary crossing that needs the same scrutiny as artifact ingestion.",
        "nix_ghsa_gr92",
    ),
    Incident(
        "cve_2026_1386",
        "2026",
        "local_attacker",
        "Firecracker jailer symlink flaw allowing arbitrary host file overwrite; fixed in 1.13.2 and 1.14.1.",
        "The jailer's host-file surface is part of the isolation TCB; symlink resolution defects escape the microVM boundary.",
        "firecracker_jailer_advisory",
    ),
    Incident(
        "cve_2026_45782",
        "2026",
        "local_attacker",
        "Cloud Hypervisor v52.0 fixing CVE-2026-45782 in the Rust VMM.",
        "MicroVM managers ship CVEs like any VMM; update operations for the virtualization layer are part of the boundary.",
        "cloud_hypervisor_v52",
    ),
)


#: Pinned offensive/defensive AI capability numbers reported by the source
#: assessment (attribution caveats recorded in the matching :data:`SOURCES`
#: entries; these are reporting-party figures, not independent measurements).
CAPABILITY_BASELINE: dict = {
    "ncsc_horizon_year": 2027,
    "anthropic_targeted_entities": 30,
    "aisi_runs_total": 122,
    "aisi_unsanctioned_runs": 10,
    "aisi_incident_days": "2026-07-25..28",
    "aixcc_year": 2025,
    "qsb_118_fix_package": "qubes-core-dom0-linux 4.3.22",
    "nixos_2605_support_end": "2026-12-31",
    # v0.2.0 extension (verified 2026-09-11).
    "ncsc_original_date": "2024-01-24",
    "gtg1002_autonomy_low_pct": 80,
    "gtg1002_autonomy_high_pct": 90,
    "gtg1002_decision_points_low": 4,
    "gtg1002_decision_points_high": 6,
    "aisi_actions": 19,
    "aisi_models": 7,
    "aixcc_identified_pct": 86,
    "aixcc_patched_pct": 68,
    "aixcc_real_vulns": 18,
    "qsb_118_cve": "CVE-2026-82636",
    "qsb_118_cvss": 7.9,
    "openai_hf_actions": 17600,
    "reproducible_iso_pct": 95.18,
    "reproducible_closure_pct": 99.48,
    "ncsc_2027_assessment_date": "2025-05-07",
    "aisi_report_published": "2026-08-04",
}


def sources_by_tier() -> dict[str, int]:
    """Return the number of sources per tier, all 5 tiers present."""
    counts = {tier: 0 for tier in TIER_VOCAB}
    for source in SOURCES:
        counts[source.tier] += 1
    return counts
